/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenapiJsClient);
  }
}(this, function(expect, OpenapiJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenapiJsClient.ApiApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApiApi', function() {
    describe('apiSchemaRetrieve', function() {
      it('should call apiSchemaRetrieve successfully', function(done) {
        //uncomment below and update the code to test apiSchemaRetrieve
        //instance.apiSchemaRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiVariablesCreate', function() {
      it('should call apiVariablesCreate successfully', function(done) {
        //uncomment below and update the code to test apiVariablesCreate
        //instance.apiVariablesCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiVariablesDestroy', function() {
      it('should call apiVariablesDestroy successfully', function(done) {
        //uncomment below and update the code to test apiVariablesDestroy
        //instance.apiVariablesDestroy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiVariablesList', function() {
      it('should call apiVariablesList successfully', function(done) {
        //uncomment below and update the code to test apiVariablesList
        //instance.apiVariablesList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiVariablesRetrieve', function() {
      it('should call apiVariablesRetrieve successfully', function(done) {
        //uncomment below and update the code to test apiVariablesRetrieve
        //instance.apiVariablesRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiVariablesUpdate', function() {
      it('should call apiVariablesUpdate successfully', function(done) {
        //uncomment below and update the code to test apiVariablesUpdate
        //instance.apiVariablesUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
