/**
 * Data Streaming - OpenAPI
 * The Data Streaming API allows you to manage your existing data streamings and templates. Data Streaming allows you to feed your stream processing, SIEM, and big data platforms with the event logs from your applications on Azion in real time. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EndpointGoogleBigQueryServiceAccountKey from './EndpointGoogleBigQueryServiceAccountKey';

/**
 * The EndpointGoogleBigQuery model module.
 * @module model/EndpointGoogleBigQuery
 * @version 1.0.0
 */
class EndpointGoogleBigQuery {
    /**
     * Constructs a new <code>EndpointGoogleBigQuery</code>.
     * @alias module:model/EndpointGoogleBigQuery
     */
    constructor() { 
        
        EndpointGoogleBigQuery.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EndpointGoogleBigQuery</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EndpointGoogleBigQuery} obj Optional instance to populate.
     * @return {module:model/EndpointGoogleBigQuery} The populated <code>EndpointGoogleBigQuery</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EndpointGoogleBigQuery();

            if (data.hasOwnProperty('endpoint_type')) {
                obj['endpoint_type'] = ApiClient.convertToType(data['endpoint_type'], 'String');
            }
            if (data.hasOwnProperty('dataset_id')) {
                obj['dataset_id'] = ApiClient.convertToType(data['dataset_id'], 'String');
            }
            if (data.hasOwnProperty('project_id')) {
                obj['project_id'] = ApiClient.convertToType(data['project_id'], 'String');
            }
            if (data.hasOwnProperty('table_id')) {
                obj['table_id'] = ApiClient.convertToType(data['table_id'], 'String');
            }
            if (data.hasOwnProperty('service_account_key')) {
                obj['service_account_key'] = EndpointGoogleBigQueryServiceAccountKey.constructFromObject(data['service_account_key']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EndpointGoogleBigQuery</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EndpointGoogleBigQuery</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['endpoint_type'] && !(typeof data['endpoint_type'] === 'string' || data['endpoint_type'] instanceof String)) {
            throw new Error("Expected the field `endpoint_type` to be a primitive type in the JSON string but got " + data['endpoint_type']);
        }
        // ensure the json data is a string
        if (data['dataset_id'] && !(typeof data['dataset_id'] === 'string' || data['dataset_id'] instanceof String)) {
            throw new Error("Expected the field `dataset_id` to be a primitive type in the JSON string but got " + data['dataset_id']);
        }
        // ensure the json data is a string
        if (data['project_id'] && !(typeof data['project_id'] === 'string' || data['project_id'] instanceof String)) {
            throw new Error("Expected the field `project_id` to be a primitive type in the JSON string but got " + data['project_id']);
        }
        // ensure the json data is a string
        if (data['table_id'] && !(typeof data['table_id'] === 'string' || data['table_id'] instanceof String)) {
            throw new Error("Expected the field `table_id` to be a primitive type in the JSON string but got " + data['table_id']);
        }
        // validate the optional field `service_account_key`
        if (data['service_account_key']) { // data not null
          EndpointGoogleBigQueryServiceAccountKey.validateJSON(data['service_account_key']);
        }

        return true;
    }


}



/**
 * @member {String} endpoint_type
 */
EndpointGoogleBigQuery.prototype['endpoint_type'] = undefined;

/**
 * @member {String} dataset_id
 */
EndpointGoogleBigQuery.prototype['dataset_id'] = undefined;

/**
 * @member {String} project_id
 */
EndpointGoogleBigQuery.prototype['project_id'] = undefined;

/**
 * @member {String} table_id
 */
EndpointGoogleBigQuery.prototype['table_id'] = undefined;

/**
 * @member {module:model/EndpointGoogleBigQueryServiceAccountKey} service_account_key
 */
EndpointGoogleBigQuery.prototype['service_account_key'] = undefined;






export default EndpointGoogleBigQuery;

