/**
 * Data Streaming - OpenAPI
 * The Data Streaming API allows you to manage your existing data streamings and templates. Data Streaming allows you to feed your stream processing, SIEM, and big data platforms with the event logs from your applications on Azion in real time. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EndpoinrtS3 model module.
 * @module model/EndpoinrtS3
 * @version 1.0.0
 */
class EndpoinrtS3 {
    /**
     * Constructs a new <code>EndpoinrtS3</code>.
     * @alias module:model/EndpoinrtS3
     */
    constructor() { 
        
        EndpoinrtS3.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EndpoinrtS3</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EndpoinrtS3} obj Optional instance to populate.
     * @return {module:model/EndpoinrtS3} The populated <code>EndpoinrtS3</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EndpoinrtS3();

            if (data.hasOwnProperty('endpoint_type')) {
                obj['endpoint_type'] = ApiClient.convertToType(data['endpoint_type'], 'String');
            }
            if (data.hasOwnProperty('access_key')) {
                obj['access_key'] = ApiClient.convertToType(data['access_key'], 'String');
            }
            if (data.hasOwnProperty('region')) {
                obj['region'] = ApiClient.convertToType(data['region'], 'String');
            }
            if (data.hasOwnProperty('object_key_prefix')) {
                obj['object_key_prefix'] = ApiClient.convertToType(data['object_key_prefix'], 'String');
            }
            if (data.hasOwnProperty('bucket_name')) {
                obj['bucket_name'] = ApiClient.convertToType(data['bucket_name'], 'String');
            }
            if (data.hasOwnProperty('content_type')) {
                obj['content_type'] = ApiClient.convertToType(data['content_type'], 'String');
            }
            if (data.hasOwnProperty('host_url')) {
                obj['host_url'] = ApiClient.convertToType(data['host_url'], 'String');
            }
            if (data.hasOwnProperty('secret_key')) {
                obj['secret_key'] = ApiClient.convertToType(data['secret_key'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EndpoinrtS3</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EndpoinrtS3</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['endpoint_type'] && !(typeof data['endpoint_type'] === 'string' || data['endpoint_type'] instanceof String)) {
            throw new Error("Expected the field `endpoint_type` to be a primitive type in the JSON string but got " + data['endpoint_type']);
        }
        // ensure the json data is a string
        if (data['access_key'] && !(typeof data['access_key'] === 'string' || data['access_key'] instanceof String)) {
            throw new Error("Expected the field `access_key` to be a primitive type in the JSON string but got " + data['access_key']);
        }
        // ensure the json data is a string
        if (data['region'] && !(typeof data['region'] === 'string' || data['region'] instanceof String)) {
            throw new Error("Expected the field `region` to be a primitive type in the JSON string but got " + data['region']);
        }
        // ensure the json data is a string
        if (data['object_key_prefix'] && !(typeof data['object_key_prefix'] === 'string' || data['object_key_prefix'] instanceof String)) {
            throw new Error("Expected the field `object_key_prefix` to be a primitive type in the JSON string but got " + data['object_key_prefix']);
        }
        // ensure the json data is a string
        if (data['bucket_name'] && !(typeof data['bucket_name'] === 'string' || data['bucket_name'] instanceof String)) {
            throw new Error("Expected the field `bucket_name` to be a primitive type in the JSON string but got " + data['bucket_name']);
        }
        // ensure the json data is a string
        if (data['content_type'] && !(typeof data['content_type'] === 'string' || data['content_type'] instanceof String)) {
            throw new Error("Expected the field `content_type` to be a primitive type in the JSON string but got " + data['content_type']);
        }
        // ensure the json data is a string
        if (data['host_url'] && !(typeof data['host_url'] === 'string' || data['host_url'] instanceof String)) {
            throw new Error("Expected the field `host_url` to be a primitive type in the JSON string but got " + data['host_url']);
        }
        // ensure the json data is a string
        if (data['secret_key'] && !(typeof data['secret_key'] === 'string' || data['secret_key'] instanceof String)) {
            throw new Error("Expected the field `secret_key` to be a primitive type in the JSON string but got " + data['secret_key']);
        }

        return true;
    }


}



/**
 * @member {String} endpoint_type
 */
EndpoinrtS3.prototype['endpoint_type'] = undefined;

/**
 * @member {String} access_key
 */
EndpoinrtS3.prototype['access_key'] = undefined;

/**
 * @member {String} region
 */
EndpoinrtS3.prototype['region'] = undefined;

/**
 * @member {String} object_key_prefix
 */
EndpoinrtS3.prototype['object_key_prefix'] = undefined;

/**
 * @member {String} bucket_name
 */
EndpoinrtS3.prototype['bucket_name'] = undefined;

/**
 * @member {String} content_type
 */
EndpoinrtS3.prototype['content_type'] = undefined;

/**
 * @member {String} host_url
 */
EndpoinrtS3.prototype['host_url'] = undefined;

/**
 * @member {String} secret_key
 */
EndpoinrtS3.prototype['secret_key'] = undefined;






export default EndpoinrtS3;

