/**
 * Data Streaming - OpenAPI
 * The Data Streaming API allows you to manage your existing data streamings and templates. Data Streaming allows you to feed your stream processing, SIEM, and big data platforms with the event logs from your applications on Azion in real time. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Template from './Template';

/**
 * The TemplateResultById model module.
 * @module model/TemplateResultById
 * @version 1.0.0
 */
class TemplateResultById {
    /**
     * Constructs a new <code>TemplateResultById</code>.
     * @alias module:model/TemplateResultById
     */
    constructor() { 
        
        TemplateResultById.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TemplateResultById</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TemplateResultById} obj Optional instance to populate.
     * @return {module:model/TemplateResultById} The populated <code>TemplateResultById</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TemplateResultById();

            if (data.hasOwnProperty('results')) {
                obj['results'] = Template.constructFromObject(data['results']);
            }
            if (data.hasOwnProperty('schema_version')) {
                obj['schema_version'] = ApiClient.convertToType(data['schema_version'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TemplateResultById</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TemplateResultById</code>.
     */
    static validateJSON(data) {
        // validate the optional field `results`
        if (data['results']) { // data not null
          Template.validateJSON(data['results']);
        }

        return true;
    }


}



/**
 * @member {module:model/Template} results
 */
TemplateResultById.prototype['results'] = undefined;

/**
 * @member {Number} schema_version
 */
TemplateResultById.prototype['schema_version'] = undefined;






export default TemplateResultById;

