/**
 * Edge Functions Instances API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import CreateEdgeFunctionsInstancesRequest from './model/CreateEdgeFunctionsInstancesRequest';
import EdgeFunctionsInstance from './model/EdgeFunctionsInstance';
import EdgeFunctionsInstanceResponse from './model/EdgeFunctionsInstanceResponse';
import Links from './model/Links';
import ListEdgeFunctionsInstancesResponse from './model/ListEdgeFunctionsInstancesResponse';
import DefaultApi from './api/DefaultApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var EdgeFunctionsInstancesApi = require('index'); // See note below*.
* var xxxSvc = new EdgeFunctionsInstancesApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new EdgeFunctionsInstancesApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new EdgeFunctionsInstancesApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new EdgeFunctionsInstancesApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The CreateEdgeFunctionsInstancesRequest model constructor.
     * @property {module:model/CreateEdgeFunctionsInstancesRequest}
     */
    CreateEdgeFunctionsInstancesRequest,

    /**
     * The EdgeFunctionsInstance model constructor.
     * @property {module:model/EdgeFunctionsInstance}
     */
    EdgeFunctionsInstance,

    /**
     * The EdgeFunctionsInstanceResponse model constructor.
     * @property {module:model/EdgeFunctionsInstanceResponse}
     */
    EdgeFunctionsInstanceResponse,

    /**
     * The Links model constructor.
     * @property {module:model/Links}
     */
    Links,

    /**
     * The ListEdgeFunctionsInstancesResponse model constructor.
     * @property {module:model/ListEdgeFunctionsInstancesResponse}
     */
    ListEdgeFunctionsInstancesResponse,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
