/**
 * Edge Application API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DeviceGroupsResponseLinks from './DeviceGroupsResponseLinks';
import DeviceGroupsResultResponse from './DeviceGroupsResultResponse';

/**
 * The DeviceGroupsResponse model module.
 * @module model/DeviceGroupsResponse
 * @version 2.0.0
 */
class DeviceGroupsResponse {
    /**
     * Constructs a new <code>DeviceGroupsResponse</code>.
     * @alias module:model/DeviceGroupsResponse
     * @param count {Number} 
     * @param totalPages {Number} 
     * @param schemaVersion {Number} 
     * @param links {module:model/DeviceGroupsResponseLinks} 
     * @param results {Array.<module:model/DeviceGroupsResultResponse>} 
     */
    constructor(count, totalPages, schemaVersion, links, results) { 
        
        DeviceGroupsResponse.initialize(this, count, totalPages, schemaVersion, links, results);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, count, totalPages, schemaVersion, links, results) { 
        obj['count'] = count;
        obj['total_pages'] = totalPages;
        obj['schema_version'] = schemaVersion;
        obj['links'] = links;
        obj['results'] = results;
    }

    /**
     * Constructs a <code>DeviceGroupsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeviceGroupsResponse} obj Optional instance to populate.
     * @return {module:model/DeviceGroupsResponse} The populated <code>DeviceGroupsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeviceGroupsResponse();

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('total_pages')) {
                obj['total_pages'] = ApiClient.convertToType(data['total_pages'], 'Number');
            }
            if (data.hasOwnProperty('schema_version')) {
                obj['schema_version'] = ApiClient.convertToType(data['schema_version'], 'Number');
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = DeviceGroupsResponseLinks.constructFromObject(data['links']);
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [DeviceGroupsResultResponse]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeviceGroupsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeviceGroupsResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DeviceGroupsResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `links`
        if (data['links']) { // data not null
          DeviceGroupsResponseLinks.validateJSON(data['links']);
        }
        if (data['results']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['results'])) {
                throw new Error("Expected the field `results` to be an array in the JSON data but got " + data['results']);
            }
            // validate the optional field `results` (array)
            for (const item of data['results']) {
                DeviceGroupsResultResponse.validateJSON(item);
            };
        }

        return true;
    }


}

DeviceGroupsResponse.RequiredProperties = ["count", "total_pages", "schema_version", "links", "results"];

/**
 * @member {Number} count
 */
DeviceGroupsResponse.prototype['count'] = undefined;

/**
 * @member {Number} total_pages
 */
DeviceGroupsResponse.prototype['total_pages'] = undefined;

/**
 * @member {Number} schema_version
 */
DeviceGroupsResponse.prototype['schema_version'] = undefined;

/**
 * @member {module:model/DeviceGroupsResponseLinks} links
 */
DeviceGroupsResponse.prototype['links'] = undefined;

/**
 * @member {Array.<module:model/DeviceGroupsResultResponse>} results
 */
DeviceGroupsResponse.prototype['results'] = undefined;






export default DeviceGroupsResponse;

