/**
 * Edge Application API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApplicationLinks from './ApplicationLinks';
import ApplicationsResults from './ApplicationsResults';

/**
 * The GetApplicationsResponse model module.
 * @module model/GetApplicationsResponse
 * @version 2.0.0
 */
class GetApplicationsResponse {
    /**
     * Constructs a new <code>GetApplicationsResponse</code>.
     * @alias module:model/GetApplicationsResponse
     * @param count {Number} 
     * @param totalPages {Number} 
     * @param schemaVersion {Number} 
     * @param links {module:model/ApplicationLinks} 
     * @param results {Array.<module:model/ApplicationsResults>} 
     */
    constructor(count, totalPages, schemaVersion, links, results) { 
        
        GetApplicationsResponse.initialize(this, count, totalPages, schemaVersion, links, results);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, count, totalPages, schemaVersion, links, results) { 
        obj['count'] = count;
        obj['total_pages'] = totalPages;
        obj['schema_version'] = schemaVersion;
        obj['links'] = links;
        obj['results'] = results;
    }

    /**
     * Constructs a <code>GetApplicationsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetApplicationsResponse} obj Optional instance to populate.
     * @return {module:model/GetApplicationsResponse} The populated <code>GetApplicationsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetApplicationsResponse();

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('total_pages')) {
                obj['total_pages'] = ApiClient.convertToType(data['total_pages'], 'Number');
            }
            if (data.hasOwnProperty('schema_version')) {
                obj['schema_version'] = ApiClient.convertToType(data['schema_version'], 'Number');
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApplicationLinks.constructFromObject(data['links']);
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [ApplicationsResults]);
            }
            if (data.hasOwnProperty('next')) {
                obj['next'] = ApiClient.convertToType(data['next'], 'String');
            }
            if (data.hasOwnProperty('previous')) {
                obj['previous'] = ApiClient.convertToType(data['previous'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetApplicationsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetApplicationsResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetApplicationsResponse.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `links`
        if (data['links']) { // data not null
          ApplicationLinks.validateJSON(data['links']);
        }
        if (data['results']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['results'])) {
                throw new Error("Expected the field `results` to be an array in the JSON data but got " + data['results']);
            }
            // validate the optional field `results` (array)
            for (const item of data['results']) {
                ApplicationsResults.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['next'] && !(typeof data['next'] === 'string' || data['next'] instanceof String)) {
            throw new Error("Expected the field `next` to be a primitive type in the JSON string but got " + data['next']);
        }
        // ensure the json data is a string
        if (data['previous'] && !(typeof data['previous'] === 'string' || data['previous'] instanceof String)) {
            throw new Error("Expected the field `previous` to be a primitive type in the JSON string but got " + data['previous']);
        }

        return true;
    }


}

GetApplicationsResponse.RequiredProperties = ["count", "total_pages", "schema_version", "links", "results"];

/**
 * @member {Number} count
 */
GetApplicationsResponse.prototype['count'] = undefined;

/**
 * @member {Number} total_pages
 */
GetApplicationsResponse.prototype['total_pages'] = undefined;

/**
 * @member {Number} schema_version
 */
GetApplicationsResponse.prototype['schema_version'] = undefined;

/**
 * @member {module:model/ApplicationLinks} links
 */
GetApplicationsResponse.prototype['links'] = undefined;

/**
 * @member {Array.<module:model/ApplicationsResults>} results
 */
GetApplicationsResponse.prototype['results'] = undefined;

/**
 * @member {String} next
 */
GetApplicationsResponse.prototype['next'] = undefined;

/**
 * @member {String} previous
 */
GetApplicationsResponse.prototype['previous'] = undefined;






export default GetApplicationsResponse;

