/**
 * Edge Application API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApplicationResults from './ApplicationResults';

/**
 * The GetApplicationResponse model module.
 * @module model/GetApplicationResponse
 * @version 2.0.0
 */
class GetApplicationResponse {
    /**
     * Constructs a new <code>GetApplicationResponse</code>.
     * @alias module:model/GetApplicationResponse
     * @param results {module:model/ApplicationResults} 
     * @param schemaVersion {Number} 
     */
    constructor(results, schemaVersion) { 
        
        GetApplicationResponse.initialize(this, results, schemaVersion);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, results, schemaVersion) { 
        obj['results'] = results;
        obj['schema_version'] = schemaVersion;
    }

    /**
     * Constructs a <code>GetApplicationResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetApplicationResponse} obj Optional instance to populate.
     * @return {module:model/GetApplicationResponse} The populated <code>GetApplicationResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetApplicationResponse();

            if (data.hasOwnProperty('results')) {
                obj['results'] = ApplicationResults.constructFromObject(data['results']);
            }
            if (data.hasOwnProperty('schema_version')) {
                obj['schema_version'] = ApiClient.convertToType(data['schema_version'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetApplicationResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetApplicationResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetApplicationResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `results`
        if (data['results']) { // data not null
          ApplicationResults.validateJSON(data['results']);
        }

        return true;
    }


}

GetApplicationResponse.RequiredProperties = ["results", "schema_version"];

/**
 * @member {module:model/ApplicationResults} results
 */
GetApplicationResponse.prototype['results'] = undefined;

/**
 * @member {Number} schema_version
 */
GetApplicationResponse.prototype['schema_version'] = undefined;






export default GetApplicationResponse;

