/**
 * Edge Application API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OriginsResultResponseAddresses model module.
 * @module model/OriginsResultResponseAddresses
 * @version 2.0.0
 */
class OriginsResultResponseAddresses {
    /**
     * Constructs a new <code>OriginsResultResponseAddresses</code>.
     * @alias module:model/OriginsResultResponseAddresses
     * @param address {String} 
     * @param weight {Number} 
     * @param serverRole {String} 
     * @param isActive {Boolean} 
     */
    constructor(address, weight, serverRole, isActive) { 
        
        OriginsResultResponseAddresses.initialize(this, address, weight, serverRole, isActive);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, address, weight, serverRole, isActive) { 
        obj['address'] = address;
        obj['weight'] = weight;
        obj['server_role'] = serverRole;
        obj['is_active'] = isActive;
    }

    /**
     * Constructs a <code>OriginsResultResponseAddresses</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OriginsResultResponseAddresses} obj Optional instance to populate.
     * @return {module:model/OriginsResultResponseAddresses} The populated <code>OriginsResultResponseAddresses</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OriginsResultResponseAddresses();

            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('weight')) {
                obj['weight'] = ApiClient.convertToType(data['weight'], 'Number');
            }
            if (data.hasOwnProperty('server_role')) {
                obj['server_role'] = ApiClient.convertToType(data['server_role'], 'String');
            }
            if (data.hasOwnProperty('is_active')) {
                obj['is_active'] = ApiClient.convertToType(data['is_active'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OriginsResultResponseAddresses</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OriginsResultResponseAddresses</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OriginsResultResponseAddresses.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }
        // ensure the json data is a string
        if (data['server_role'] && !(typeof data['server_role'] === 'string' || data['server_role'] instanceof String)) {
            throw new Error("Expected the field `server_role` to be a primitive type in the JSON string but got " + data['server_role']);
        }

        return true;
    }


}

OriginsResultResponseAddresses.RequiredProperties = ["address", "weight", "server_role", "is_active"];

/**
 * @member {String} address
 */
OriginsResultResponseAddresses.prototype['address'] = undefined;

/**
 * @member {Number} weight
 */
OriginsResultResponseAddresses.prototype['weight'] = undefined;

/**
 * @member {String} server_role
 */
OriginsResultResponseAddresses.prototype['server_role'] = undefined;

/**
 * @member {Boolean} is_active
 */
OriginsResultResponseAddresses.prototype['is_active'] = undefined;






export default OriginsResultResponseAddresses;

