/**
 * Edge Application API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RulesEngineBehaviorString model module.
 * @module model/RulesEngineBehaviorString
 * @version 2.0.0
 */
class RulesEngineBehaviorString {
    /**
     * Constructs a new <code>RulesEngineBehaviorString</code>.
     * @alias module:model/RulesEngineBehaviorString
     * @param name {String} 
     * @param target {String} 
     */
    constructor(name, target) { 
        
        RulesEngineBehaviorString.initialize(this, name, target);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, target) { 
        obj['name'] = name;
        obj['target'] = target;
    }

    /**
     * Constructs a <code>RulesEngineBehaviorString</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RulesEngineBehaviorString} obj Optional instance to populate.
     * @return {module:model/RulesEngineBehaviorString} The populated <code>RulesEngineBehaviorString</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RulesEngineBehaviorString();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('target')) {
                obj['target'] = ApiClient.convertToType(data['target'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RulesEngineBehaviorString</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RulesEngineBehaviorString</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RulesEngineBehaviorString.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['target'] && !(typeof data['target'] === 'string' || data['target'] instanceof String)) {
            throw new Error("Expected the field `target` to be a primitive type in the JSON string but got " + data['target']);
        }

        return true;
    }


}

RulesEngineBehaviorString.RequiredProperties = ["name", "target"];

/**
 * @member {String} name
 */
RulesEngineBehaviorString.prototype['name'] = undefined;

/**
 * @member {String} target
 */
RulesEngineBehaviorString.prototype['target'] = undefined;






export default RulesEngineBehaviorString;

