/**
 * Edge Firewall API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EdgeFirewallApi);
  }
}(this, function(expect, EdgeFirewallApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EdgeFirewallApi.EdgeFirewall();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EdgeFirewall', function() {
    it('should create an instance of EdgeFirewall', function() {
      // uncomment below and update the code to test EdgeFirewall
      //var instance = new EdgeFirewallApi.EdgeFirewall();
      //expect(instance).to.be.a(EdgeFirewallApi.EdgeFirewall);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new EdgeFirewallApi.EdgeFirewall();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new EdgeFirewallApi.EdgeFirewall();
      //expect(instance).to.be();
    });

    it('should have the property isActive (base name: "is_active")', function() {
      // uncomment below and update the code to test the property isActive
      //var instance = new EdgeFirewallApi.EdgeFirewall();
      //expect(instance).to.be();
    });

    it('should have the property lastEditor (base name: "last_editor")', function() {
      // uncomment below and update the code to test the property lastEditor
      //var instance = new EdgeFirewallApi.EdgeFirewall();
      //expect(instance).to.be();
    });

    it('should have the property lastModified (base name: "last_modified")', function() {
      // uncomment below and update the code to test the property lastModified
      //var instance = new EdgeFirewallApi.EdgeFirewall();
      //expect(instance).to.be();
    });

    it('should have the property edgeFunctionsEnabled (base name: "edge_functions_enabled")', function() {
      // uncomment below and update the code to test the property edgeFunctionsEnabled
      //var instance = new EdgeFirewallApi.EdgeFirewall();
      //expect(instance).to.be();
    });

    it('should have the property networkProtectionEnabled (base name: "network_protection_enabled")', function() {
      // uncomment below and update the code to test the property networkProtectionEnabled
      //var instance = new EdgeFirewallApi.EdgeFirewall();
      //expect(instance).to.be();
    });

    it('should have the property wafEnabled (base name: "waf_enabled")', function() {
      // uncomment below and update the code to test the property wafEnabled
      //var instance = new EdgeFirewallApi.EdgeFirewall();
      //expect(instance).to.be();
    });

    it('should have the property debugRules (base name: "debug_rules")', function() {
      // uncomment below and update the code to test the property debugRules
      //var instance = new EdgeFirewallApi.EdgeFirewall();
      //expect(instance).to.be();
    });

    it('should have the property domains (base name: "domains")', function() {
      // uncomment below and update the code to test the property domains
      //var instance = new EdgeFirewallApi.EdgeFirewall();
      //expect(instance).to.be();
    });

  });

}));
