/**
 * Web Application Firewall API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WAFEvents200ResultsInnerTop10CountriesInner from './WAFEvents200ResultsInnerTop10CountriesInner';

/**
 * The WAFEvents200ResultsInner model module.
 * @module model/WAFEvents200ResultsInner
 * @version 2.0.0
 */
class WAFEvents200ResultsInner {
    /**
     * Constructs a new <code>WAFEvents200ResultsInner</code>.
     * @alias module:model/WAFEvents200ResultsInner
     */
    constructor() { 
        
        WAFEvents200ResultsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WAFEvents200ResultsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WAFEvents200ResultsInner} obj Optional instance to populate.
     * @return {module:model/WAFEvents200ResultsInner} The populated <code>WAFEvents200ResultsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WAFEvents200ResultsInner();

            if (data.hasOwnProperty('country_count')) {
                obj['country_count'] = ApiClient.convertToType(data['country_count'], 'Number');
            }
            if (data.hasOwnProperty('top_10_countries')) {
                obj['top_10_countries'] = ApiClient.convertToType(data['top_10_countries'], [WAFEvents200ResultsInnerTop10CountriesInner]);
            }
            if (data.hasOwnProperty('top_10_ips')) {
                obj['top_10_ips'] = ApiClient.convertToType(data['top_10_ips'], [WAFEvents200ResultsInnerTop10CountriesInner]);
            }
            if (data.hasOwnProperty('hit_count')) {
                obj['hit_count'] = ApiClient.convertToType(data['hit_count'], 'Number');
            }
            if (data.hasOwnProperty('rule_id')) {
                obj['rule_id'] = ApiClient.convertToType(data['rule_id'], 'Number');
            }
            if (data.hasOwnProperty('ip_count')) {
                obj['ip_count'] = ApiClient.convertToType(data['ip_count'], 'Number');
            }
            if (data.hasOwnProperty('match_zone')) {
                obj['match_zone'] = ApiClient.convertToType(data['match_zone'], 'String');
            }
            if (data.hasOwnProperty('path_count')) {
                obj['path_count'] = ApiClient.convertToType(data['path_count'], 'Number');
            }
            if (data.hasOwnProperty('matches_on')) {
                obj['matches_on'] = ApiClient.convertToType(data['matches_on'], 'String');
            }
            if (data.hasOwnProperty('rule_description')) {
                obj['rule_description'] = ApiClient.convertToType(data['rule_description'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WAFEvents200ResultsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WAFEvents200ResultsInner</code>.
     */
    static validateJSON(data) {
        if (data['top_10_countries']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['top_10_countries'])) {
                throw new Error("Expected the field `top_10_countries` to be an array in the JSON data but got " + data['top_10_countries']);
            }
            // validate the optional field `top_10_countries` (array)
            for (const item of data['top_10_countries']) {
                WAFEvents200ResultsInnerTop10CountriesInner.validateJSON(item);
            };
        }
        if (data['top_10_ips']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['top_10_ips'])) {
                throw new Error("Expected the field `top_10_ips` to be an array in the JSON data but got " + data['top_10_ips']);
            }
            // validate the optional field `top_10_ips` (array)
            for (const item of data['top_10_ips']) {
                WAFEvents200ResultsInnerTop10CountriesInner.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['match_zone'] && !(typeof data['match_zone'] === 'string' || data['match_zone'] instanceof String)) {
            throw new Error("Expected the field `match_zone` to be a primitive type in the JSON string but got " + data['match_zone']);
        }
        // ensure the json data is a string
        if (data['matches_on'] && !(typeof data['matches_on'] === 'string' || data['matches_on'] instanceof String)) {
            throw new Error("Expected the field `matches_on` to be a primitive type in the JSON string but got " + data['matches_on']);
        }
        // ensure the json data is a string
        if (data['rule_description'] && !(typeof data['rule_description'] === 'string' || data['rule_description'] instanceof String)) {
            throw new Error("Expected the field `rule_description` to be a primitive type in the JSON string but got " + data['rule_description']);
        }

        return true;
    }


}



/**
 * @member {Number} country_count
 */
WAFEvents200ResultsInner.prototype['country_count'] = undefined;

/**
 * @member {Array.<module:model/WAFEvents200ResultsInnerTop10CountriesInner>} top_10_countries
 */
WAFEvents200ResultsInner.prototype['top_10_countries'] = undefined;

/**
 * @member {Array.<module:model/WAFEvents200ResultsInnerTop10CountriesInner>} top_10_ips
 */
WAFEvents200ResultsInner.prototype['top_10_ips'] = undefined;

/**
 * @member {Number} hit_count
 */
WAFEvents200ResultsInner.prototype['hit_count'] = undefined;

/**
 * @member {Number} rule_id
 */
WAFEvents200ResultsInner.prototype['rule_id'] = undefined;

/**
 * @member {Number} ip_count
 */
WAFEvents200ResultsInner.prototype['ip_count'] = undefined;

/**
 * @member {module:model/WAFEvents200ResultsInner.MatchZoneEnum} match_zone
 */
WAFEvents200ResultsInner.prototype['match_zone'] = undefined;

/**
 * @member {Number} path_count
 */
WAFEvents200ResultsInner.prototype['path_count'] = undefined;

/**
 * @member {module:model/WAFEvents200ResultsInner.MatchesOnEnum} matches_on
 */
WAFEvents200ResultsInner.prototype['matches_on'] = undefined;

/**
 * @member {String} rule_description
 */
WAFEvents200ResultsInner.prototype['rule_description'] = undefined;





/**
 * Allowed values for the <code>match_zone</code> property.
 * @enum {String}
 * @readonly
 */
WAFEvents200ResultsInner['MatchZoneEnum'] = {

    /**
     * value: "path"
     * @const
     */
    "path": "path",

    /**
     * value: "query_string"
     * @const
     */
    "query_string": "query_string",

    /**
     * value: "request_header"
     * @const
     */
    "request_header": "request_header",

    /**
     * value: "request_body"
     * @const
     */
    "request_body": "request_body",

    /**
     * value: "raw_body"
     * @const
     */
    "raw_body": "raw_body",

    /**
     * value: "file_name"
     * @const
     */
    "file_name": "file_name",

    /**
     * value: "cookie"
     * @const
     */
    "cookie": "cookie"
};


/**
 * Allowed values for the <code>matches_on</code> property.
 * @enum {String}
 * @readonly
 */
WAFEvents200ResultsInner['MatchesOnEnum'] = {

    /**
     * value: "name"
     * @const
     */
    "name": "name",

    /**
     * value: "value"
     * @const
     */
    "value": "value"
};



export default WAFEvents200ResultsInner;

