/**
 * Variables
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VariableGet model module.
 * @module model/VariableGet
 * @version 0.1.0
 */
class VariableGet {
    /**
     * Constructs a new <code>VariableGet</code>.
     * @alias module:model/VariableGet
     * @param uuid {String} 
     * @param key {String} 
     * @param value {String} Given the *incoming* primitive data, return the value for this field that should be validated and transformed to a native value.
     * @param secret {Boolean} 
     * @param lastEditor {String} 
     * @param createdAt {Date} 
     * @param updatedAt {Date} 
     */
    constructor(uuid, key, value, secret, lastEditor, createdAt, updatedAt) { 
        
        VariableGet.initialize(this, uuid, key, value, secret, lastEditor, createdAt, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, uuid, key, value, secret, lastEditor, createdAt, updatedAt) { 
        obj['uuid'] = uuid;
        obj['key'] = key;
        obj['value'] = value;
        obj['secret'] = secret;
        obj['last_editor'] = lastEditor;
        obj['created_at'] = createdAt;
        obj['updated_at'] = updatedAt;
    }

    /**
     * Constructs a <code>VariableGet</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VariableGet} obj Optional instance to populate.
     * @return {module:model/VariableGet} The populated <code>VariableGet</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VariableGet();

            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('secret')) {
                obj['secret'] = ApiClient.convertToType(data['secret'], 'Boolean');
            }
            if (data.hasOwnProperty('last_editor')) {
                obj['last_editor'] = ApiClient.convertToType(data['last_editor'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VariableGet</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VariableGet</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of VariableGet.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['uuid'] && !(typeof data['uuid'] === 'string' || data['uuid'] instanceof String)) {
            throw new Error("Expected the field `uuid` to be a primitive type in the JSON string but got " + data['uuid']);
        }
        // ensure the json data is a string
        if (data['key'] && !(typeof data['key'] === 'string' || data['key'] instanceof String)) {
            throw new Error("Expected the field `key` to be a primitive type in the JSON string but got " + data['key']);
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }
        // ensure the json data is a string
        if (data['last_editor'] && !(typeof data['last_editor'] === 'string' || data['last_editor'] instanceof String)) {
            throw new Error("Expected the field `last_editor` to be a primitive type in the JSON string but got " + data['last_editor']);
        }

        return true;
    }


}

VariableGet.RequiredProperties = ["uuid", "key", "value", "secret", "last_editor", "created_at", "updated_at"];

/**
 * @member {String} uuid
 */
VariableGet.prototype['uuid'] = undefined;

/**
 * @member {String} key
 */
VariableGet.prototype['key'] = undefined;

/**
 * Given the *incoming* primitive data, return the value for this field that should be validated and transformed to a native value.
 * @member {String} value
 */
VariableGet.prototype['value'] = undefined;

/**
 * @member {Boolean} secret
 */
VariableGet.prototype['secret'] = undefined;

/**
 * @member {String} last_editor
 */
VariableGet.prototype['last_editor'] = undefined;

/**
 * @member {Date} created_at
 */
VariableGet.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
VariableGet.prototype['updated_at'] = undefined;






export default VariableGet;

