/**
 * Purge API
 * Azion Real-Time Purge
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PurgeApi);
  }
}(this, function(expect, PurgeApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PurgeApi.RealTimePurgeApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RealTimePurgeApi', function() {
    describe('purgeCacheKey', function() {
      it('should call purgeCacheKey successfully', function(done) {
        //uncomment below and update the code to test purgeCacheKey
        //instance.purgeCacheKey(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('purgeUrl', function() {
      it('should call purgeUrl successfully', function(done) {
        //uncomment below and update the code to test purgeUrl
        //instance.purgeUrl(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('purgeWildcard', function() {
      it('should call purgeWildcard successfully', function(done) {
        //uncomment below and update the code to test purgeWildcard
        //instance.purgeWildcard(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
