/**
 * Edge Node API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AuthorizeEdgeNodesRequest from './model/AuthorizeEdgeNodesRequest';
import AuthorizeEdgeNodesResponse from './model/AuthorizeEdgeNodesResponse';
import EdgeNodeDetailResponse from './model/EdgeNodeDetailResponse';
import EdgeNodeModules from './model/EdgeNodeModules';
import EdgeNodeResponse from './model/EdgeNodeResponse';
import EdgeNodeResponseWithTotal from './model/EdgeNodeResponseWithTotal';
import NodeGroup from './model/NodeGroup';
import NodeGroupResponse from './model/NodeGroupResponse';
import ServiceBindDetailResponse from './model/ServiceBindDetailResponse';
import ServiceBindRequest from './model/ServiceBindRequest';
import ServiceResponse from './model/ServiceResponse';
import ServiceResponseWithTotal from './model/ServiceResponseWithTotal';
import UnauthorizedEdgeNodeInfo from './model/UnauthorizedEdgeNodeInfo';
import UpdateEdgeNodeResponse from './model/UpdateEdgeNodeResponse';
import UpdateServiceBindRequest from './model/UpdateServiceBindRequest';
import Variable from './model/Variable';
import DefaultApi from './api/DefaultApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var EdgeNodeApi = require('index'); // See note below*.
* var xxxSvc = new EdgeNodeApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new EdgeNodeApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new EdgeNodeApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new EdgeNodeApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AuthorizeEdgeNodesRequest model constructor.
     * @property {module:model/AuthorizeEdgeNodesRequest}
     */
    AuthorizeEdgeNodesRequest,

    /**
     * The AuthorizeEdgeNodesResponse model constructor.
     * @property {module:model/AuthorizeEdgeNodesResponse}
     */
    AuthorizeEdgeNodesResponse,

    /**
     * The EdgeNodeDetailResponse model constructor.
     * @property {module:model/EdgeNodeDetailResponse}
     */
    EdgeNodeDetailResponse,

    /**
     * The EdgeNodeModules model constructor.
     * @property {module:model/EdgeNodeModules}
     */
    EdgeNodeModules,

    /**
     * The EdgeNodeResponse model constructor.
     * @property {module:model/EdgeNodeResponse}
     */
    EdgeNodeResponse,

    /**
     * The EdgeNodeResponseWithTotal model constructor.
     * @property {module:model/EdgeNodeResponseWithTotal}
     */
    EdgeNodeResponseWithTotal,

    /**
     * The NodeGroup model constructor.
     * @property {module:model/NodeGroup}
     */
    NodeGroup,

    /**
     * The NodeGroupResponse model constructor.
     * @property {module:model/NodeGroupResponse}
     */
    NodeGroupResponse,

    /**
     * The ServiceBindDetailResponse model constructor.
     * @property {module:model/ServiceBindDetailResponse}
     */
    ServiceBindDetailResponse,

    /**
     * The ServiceBindRequest model constructor.
     * @property {module:model/ServiceBindRequest}
     */
    ServiceBindRequest,

    /**
     * The ServiceResponse model constructor.
     * @property {module:model/ServiceResponse}
     */
    ServiceResponse,

    /**
     * The ServiceResponseWithTotal model constructor.
     * @property {module:model/ServiceResponseWithTotal}
     */
    ServiceResponseWithTotal,

    /**
     * The UnauthorizedEdgeNodeInfo model constructor.
     * @property {module:model/UnauthorizedEdgeNodeInfo}
     */
    UnauthorizedEdgeNodeInfo,

    /**
     * The UpdateEdgeNodeResponse model constructor.
     * @property {module:model/UpdateEdgeNodeResponse}
     */
    UpdateEdgeNodeResponse,

    /**
     * The UpdateServiceBindRequest model constructor.
     * @property {module:model/UpdateServiceBindRequest}
     */
    UpdateServiceBindRequest,

    /**
     * The Variable model constructor.
     * @property {module:model/Variable}
     */
    Variable,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
