/**
 * Azion API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import BadRequestResponse from './model/BadRequestResponse';
import CreateNetworkListsRequest from './model/CreateNetworkListsRequest';
import ErrorModel from './model/ErrorModel';
import ErrorResponse from './model/ErrorResponse';
import Links from './model/Links';
import ListNetworkListsResponse from './model/ListNetworkListsResponse';
import NetworkLists from './model/NetworkLists';
import NetworkListsResponse from './model/NetworkListsResponse';
import UpdateNetworkListsRequest from './model/UpdateNetworkListsRequest';
import DefaultApi from './api/DefaultApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var AzionApi = require('index'); // See note below*.
* var xxxSvc = new AzionApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new AzionApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new AzionApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new AzionApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 3.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The BadRequestResponse model constructor.
     * @property {module:model/BadRequestResponse}
     */
    BadRequestResponse,

    /**
     * The CreateNetworkListsRequest model constructor.
     * @property {module:model/CreateNetworkListsRequest}
     */
    CreateNetworkListsRequest,

    /**
     * The ErrorModel model constructor.
     * @property {module:model/ErrorModel}
     */
    ErrorModel,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The Links model constructor.
     * @property {module:model/Links}
     */
    Links,

    /**
     * The ListNetworkListsResponse model constructor.
     * @property {module:model/ListNetworkListsResponse}
     */
    ListNetworkListsResponse,

    /**
     * The NetworkLists model constructor.
     * @property {module:model/NetworkLists}
     */
    NetworkLists,

    /**
     * The NetworkListsResponse model constructor.
     * @property {module:model/NetworkListsResponse}
     */
    NetworkListsResponse,

    /**
     * The UpdateNetworkListsRequest model constructor.
     * @property {module:model/UpdateNetworkListsRequest}
     */
    UpdateNetworkListsRequest,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
