/**
 * Intelligent DNS
 * Azion Intelligent DNS API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DnsSecDelegationSignerDigestType model module.
 * @module model/DnsSecDelegationSignerDigestType
 * @version 3.0.0
 */
class DnsSecDelegationSignerDigestType {
    /**
     * Constructs a new <code>DnsSecDelegationSignerDigestType</code>.
     * @alias module:model/DnsSecDelegationSignerDigestType
     */
    constructor() { 
        
        DnsSecDelegationSignerDigestType.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DnsSecDelegationSignerDigestType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DnsSecDelegationSignerDigestType} obj Optional instance to populate.
     * @return {module:model/DnsSecDelegationSignerDigestType} The populated <code>DnsSecDelegationSignerDigestType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DnsSecDelegationSignerDigestType();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DnsSecDelegationSignerDigestType</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DnsSecDelegationSignerDigestType</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['slug'] && !(typeof data['slug'] === 'string' || data['slug'] instanceof String)) {
            throw new Error("Expected the field `slug` to be a primitive type in the JSON string but got " + data['slug']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
DnsSecDelegationSignerDigestType.prototype['id'] = undefined;

/**
 * @member {String} slug
 */
DnsSecDelegationSignerDigestType.prototype['slug'] = undefined;






export default DnsSecDelegationSignerDigestType;

