/**
 * Intelligent DNS
 * Azion Intelligent DNS API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetRecordsResponseResults from './GetRecordsResponseResults';
import GetZonesResponseLinks from './GetZonesResponseLinks';

/**
 * The GetRecordsResponse model module.
 * @module model/GetRecordsResponse
 * @version 3.0.0
 */
class GetRecordsResponse {
    /**
     * Constructs a new <code>GetRecordsResponse</code>.
     * Object returned by get zone record
     * @alias module:model/GetRecordsResponse
     */
    constructor() { 
        
        GetRecordsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetRecordsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetRecordsResponse} obj Optional instance to populate.
     * @return {module:model/GetRecordsResponse} The populated <code>GetRecordsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetRecordsResponse();

            if (data.hasOwnProperty('schema_version')) {
                obj['schema_version'] = ApiClient.convertToType(data['schema_version'], 'Number');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('total_pages')) {
                obj['total_pages'] = ApiClient.convertToType(data['total_pages'], 'Number');
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = GetZonesResponseLinks.constructFromObject(data['links']);
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = GetRecordsResponseResults.constructFromObject(data['results']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetRecordsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetRecordsResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `links`
        if (data['links']) { // data not null
          GetZonesResponseLinks.validateJSON(data['links']);
        }
        // validate the optional field `results`
        if (data['results']) { // data not null
          GetRecordsResponseResults.validateJSON(data['results']);
        }

        return true;
    }


}



/**
 * The schema version
 * @member {Number} schema_version
 */
GetRecordsResponse.prototype['schema_version'] = undefined;

/**
 * Number of records
 * @member {Number} count
 */
GetRecordsResponse.prototype['count'] = undefined;

/**
 * The total pages
 * @member {Number} total_pages
 */
GetRecordsResponse.prototype['total_pages'] = undefined;

/**
 * @member {module:model/GetZonesResponseLinks} links
 */
GetRecordsResponse.prototype['links'] = undefined;

/**
 * @member {module:model/GetRecordsResponseResults} results
 */
GetRecordsResponse.prototype['results'] = undefined;






export default GetRecordsResponse;

