/**
 * Intelligent DNS
 * Azion Intelligent DNS API
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetZonesResponseLinks from './GetZonesResponseLinks';
import Zone from './Zone';

/**
 * The GetZonesResponse model module.
 * @module model/GetZonesResponse
 * @version 3.0.0
 */
class GetZonesResponse {
    /**
     * Constructs a new <code>GetZonesResponse</code>.
     * Object returned by get zones
     * @alias module:model/GetZonesResponse
     */
    constructor() { 
        
        GetZonesResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetZonesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetZonesResponse} obj Optional instance to populate.
     * @return {module:model/GetZonesResponse} The populated <code>GetZonesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetZonesResponse();

            if (data.hasOwnProperty('schema_version')) {
                obj['schema_version'] = ApiClient.convertToType(data['schema_version'], 'Number');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('total_pages')) {
                obj['total_pages'] = ApiClient.convertToType(data['total_pages'], 'Number');
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = GetZonesResponseLinks.constructFromObject(data['links']);
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [Zone]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetZonesResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetZonesResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `links`
        if (data['links']) { // data not null
          GetZonesResponseLinks.validateJSON(data['links']);
        }
        if (data['results']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['results'])) {
                throw new Error("Expected the field `results` to be an array in the JSON data but got " + data['results']);
            }
            // validate the optional field `results` (array)
            for (const item of data['results']) {
                Zone.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * The schema version
 * @member {Number} schema_version
 */
GetZonesResponse.prototype['schema_version'] = undefined;

/**
 * Number of records
 * @member {Number} count
 */
GetZonesResponse.prototype['count'] = undefined;

/**
 * The total pages
 * @member {Number} total_pages
 */
GetZonesResponse.prototype['total_pages'] = undefined;

/**
 * @member {module:model/GetZonesResponseLinks} links
 */
GetZonesResponse.prototype['links'] = undefined;

/**
 * Hosted zones collection
 * @member {Array.<module:model/Zone>} results
 */
GetZonesResponse.prototype['results'] = undefined;






export default GetZonesResponse;

