/**
 * Edge Function
 * Azion Edge Function API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EdgeFunction);
  }
}(this, function(expect, EdgeFunction) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EdgeFunction.EdgeFunctionsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EdgeFunctionsApi', function() {
    describe('edgeFunctionsGet', function() {
      it('should call edgeFunctionsGet successfully', function(done) {
        //uncomment below and update the code to test edgeFunctionsGet
        //instance.edgeFunctionsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('edgeFunctionsIdDelete', function() {
      it('should call edgeFunctionsIdDelete successfully', function(done) {
        //uncomment below and update the code to test edgeFunctionsIdDelete
        //instance.edgeFunctionsIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('edgeFunctionsIdGet', function() {
      it('should call edgeFunctionsIdGet successfully', function(done) {
        //uncomment below and update the code to test edgeFunctionsIdGet
        //instance.edgeFunctionsIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('edgeFunctionsIdPatch', function() {
      it('should call edgeFunctionsIdPatch successfully', function(done) {
        //uncomment below and update the code to test edgeFunctionsIdPatch
        //instance.edgeFunctionsIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('edgeFunctionsIdPut', function() {
      it('should call edgeFunctionsIdPut successfully', function(done) {
        //uncomment below and update the code to test edgeFunctionsIdPut
        //instance.edgeFunctionsIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('edgeFunctionsPost', function() {
      it('should call edgeFunctionsPost successfully', function(done) {
        //uncomment below and update the code to test edgeFunctionsPost
        //instance.edgeFunctionsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
