/**
 * Purge API
 * Azion Real-Time Purge
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import PurgeCacheKeyRequest from './model/PurgeCacheKeyRequest';
import PurgeUrlRequest from './model/PurgeUrlRequest';
import PurgeWildcardRequest from './model/PurgeWildcardRequest';
import RealTimePurgeApi from './api/RealTimePurgeApi';


/**
* Azion Real-Time Purge.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var PurgeApi = require('index'); // See note below*.
* var xxxSvc = new PurgeApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new PurgeApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new PurgeApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new PurgeApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The PurgeCacheKeyRequest model constructor.
     * @property {module:model/PurgeCacheKeyRequest}
     */
    PurgeCacheKeyRequest,

    /**
     * The PurgeUrlRequest model constructor.
     * @property {module:model/PurgeUrlRequest}
     */
    PurgeUrlRequest,

    /**
     * The PurgeWildcardRequest model constructor.
     * @property {module:model/PurgeWildcardRequest}
     */
    PurgeWildcardRequest,

    /**
    * The RealTimePurgeApi service constructor.
    * @property {module:api/RealTimePurgeApi}
    */
    RealTimePurgeApi
};
