/**
 * Edgenode API
 * Azion Orchestration
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthorizeEdgeNodesRequest model module.
 * @module model/AuthorizeEdgeNodesRequest
 * @version 2.0.0
 */
class AuthorizeEdgeNodesRequest {
    /**
     * Constructs a new <code>AuthorizeEdgeNodesRequest</code>.
     * @alias module:model/AuthorizeEdgeNodesRequest
     * @param edgeNodeIds {Array.<Number>} 
     */
    constructor(edgeNodeIds) { 
        
        AuthorizeEdgeNodesRequest.initialize(this, edgeNodeIds);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, edgeNodeIds) { 
        obj['edge_node_ids'] = edgeNodeIds;
    }

    /**
     * Constructs a <code>AuthorizeEdgeNodesRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthorizeEdgeNodesRequest} obj Optional instance to populate.
     * @return {module:model/AuthorizeEdgeNodesRequest} The populated <code>AuthorizeEdgeNodesRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthorizeEdgeNodesRequest();

            if (data.hasOwnProperty('edge_node_ids')) {
                obj['edge_node_ids'] = ApiClient.convertToType(data['edge_node_ids'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuthorizeEdgeNodesRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuthorizeEdgeNodesRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AuthorizeEdgeNodesRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['edge_node_ids'])) {
            throw new Error("Expected the field `edge_node_ids` to be an array in the JSON data but got " + data['edge_node_ids']);
        }

        return true;
    }


}

AuthorizeEdgeNodesRequest.RequiredProperties = ["edge_node_ids"];

/**
 * @member {Array.<Number>} edge_node_ids
 */
AuthorizeEdgeNodesRequest.prototype['edge_node_ids'] = undefined;






export default AuthorizeEdgeNodesRequest;

