/**
 * Edgenode API
 * Azion Orchestration
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EdgeNodeModules model module.
 * @module model/EdgeNodeModules
 * @version 2.0.0
 */
class EdgeNodeModules {
    /**
     * Constructs a new <code>EdgeNodeModules</code>.
     * @alias module:model/EdgeNodeModules
     * @param addServices {Boolean} 
     */
    constructor(addServices) { 
        
        EdgeNodeModules.initialize(this, addServices);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, addServices) { 
        obj['add_services'] = addServices;
    }

    /**
     * Constructs a <code>EdgeNodeModules</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EdgeNodeModules} obj Optional instance to populate.
     * @return {module:model/EdgeNodeModules} The populated <code>EdgeNodeModules</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EdgeNodeModules();

            if (data.hasOwnProperty('add_services')) {
                obj['add_services'] = ApiClient.convertToType(data['add_services'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EdgeNodeModules</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EdgeNodeModules</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EdgeNodeModules.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

EdgeNodeModules.RequiredProperties = ["add_services"];

/**
 * @member {Boolean} add_services
 */
EdgeNodeModules.prototype['add_services'] = undefined;






export default EdgeNodeModules;

