/**
 * Personal Tokens - OpenAPI
 * The Personal Tokens API allows you to manage your existing personal tokens. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PersonalTokensOpenApi);
  }
}(this, function(expect, PersonalTokensOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PersonalTokensOpenApi.PersonalTokenApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PersonalTokenApi', function() {
    describe('createPersonalToken', function() {
      it('should call createPersonalToken successfully', function(done) {
        //uncomment below and update the code to test createPersonalToken
        //instance.createPersonalToken(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deletePersonalToken', function() {
      it('should call deletePersonalToken successfully', function(done) {
        //uncomment below and update the code to test deletePersonalToken
        //instance.deletePersonalToken(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPersonalToken', function() {
      it('should call getPersonalToken successfully', function(done) {
        //uncomment below and update the code to test getPersonalToken
        //instance.getPersonalToken(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listPersonalToken', function() {
      it('should call listPersonalToken successfully', function(done) {
        //uncomment below and update the code to test listPersonalToken
        //instance.listPersonalToken(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
