/**
 * Object Storage
 * REST API OpenAPI documentation for the Object Storage
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Bucket from './model/Bucket';
import BucketCreate from './model/BucketCreate';
import BucketObject from './model/BucketObject';
import EdgeAccessEnum from './model/EdgeAccessEnum';
import ObjectResponseData from './model/ObjectResponseData';
import PaginatedBucketList from './model/PaginatedBucketList';
import PaginatedBucketObjectList from './model/PaginatedBucketObjectList';
import ResponseBucket from './model/ResponseBucket';
import StateEnum from './model/StateEnum';
import SuccessBucketOperation from './model/SuccessBucketOperation';
import SuccessObjectOperation from './model/SuccessObjectOperation';
import StorageApi from './api/StorageApi';


/**
* REST API OpenAPI documentation for the Object Storage.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ObjectStorage = require('index'); // See note below*.
* var xxxSvc = new ObjectStorage.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ObjectStorage.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ObjectStorage.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ObjectStorage.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0 (v1)
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Bucket model constructor.
     * @property {module:model/Bucket}
     */
    Bucket,

    /**
     * The BucketCreate model constructor.
     * @property {module:model/BucketCreate}
     */
    BucketCreate,

    /**
     * The BucketObject model constructor.
     * @property {module:model/BucketObject}
     */
    BucketObject,

    /**
     * The EdgeAccessEnum model constructor.
     * @property {module:model/EdgeAccessEnum}
     */
    EdgeAccessEnum,

    /**
     * The ObjectResponseData model constructor.
     * @property {module:model/ObjectResponseData}
     */
    ObjectResponseData,

    /**
     * The PaginatedBucketList model constructor.
     * @property {module:model/PaginatedBucketList}
     */
    PaginatedBucketList,

    /**
     * The PaginatedBucketObjectList model constructor.
     * @property {module:model/PaginatedBucketObjectList}
     */
    PaginatedBucketObjectList,

    /**
     * The ResponseBucket model constructor.
     * @property {module:model/ResponseBucket}
     */
    ResponseBucket,

    /**
     * The StateEnum model constructor.
     * @property {module:model/StateEnum}
     */
    StateEnum,

    /**
     * The SuccessBucketOperation model constructor.
     * @property {module:model/SuccessBucketOperation}
     */
    SuccessBucketOperation,

    /**
     * The SuccessObjectOperation model constructor.
     * @property {module:model/SuccessObjectOperation}
     */
    SuccessObjectOperation,

    /**
    * The StorageApi service constructor.
    * @property {module:api/StorageApi}
    */
    StorageApi
};
