/**
 * Edge Function API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import BadRequestResponse from './model/BadRequestResponse';
import CreateEdgeFunctionRequest from './model/CreateEdgeFunctionRequest';
import EdgeFunctionResponse from './model/EdgeFunctionResponse';
import ErrorResponse from './model/ErrorResponse';
import Links from './model/Links';
import ListEdgeFunctionResponse from './model/ListEdgeFunctionResponse';
import PatchEdgeFunctionRequest from './model/PatchEdgeFunctionRequest';
import PutEdgeFunctionRequest from './model/PutEdgeFunctionRequest';
import Results from './model/Results';
import EdgeFunctionsApi from './api/EdgeFunctionsApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var EdgeFunctionApi = require('index'); // See note below*.
* var xxxSvc = new EdgeFunctionApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new EdgeFunctionApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new EdgeFunctionApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new EdgeFunctionApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The BadRequestResponse model constructor.
     * @property {module:model/BadRequestResponse}
     */
    BadRequestResponse,

    /**
     * The CreateEdgeFunctionRequest model constructor.
     * @property {module:model/CreateEdgeFunctionRequest}
     */
    CreateEdgeFunctionRequest,

    /**
     * The EdgeFunctionResponse model constructor.
     * @property {module:model/EdgeFunctionResponse}
     */
    EdgeFunctionResponse,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The Links model constructor.
     * @property {module:model/Links}
     */
    Links,

    /**
     * The ListEdgeFunctionResponse model constructor.
     * @property {module:model/ListEdgeFunctionResponse}
     */
    ListEdgeFunctionResponse,

    /**
     * The PatchEdgeFunctionRequest model constructor.
     * @property {module:model/PatchEdgeFunctionRequest}
     */
    PatchEdgeFunctionRequest,

    /**
     * The PutEdgeFunctionRequest model constructor.
     * @property {module:model/PutEdgeFunctionRequest}
     */
    PutEdgeFunctionRequest,

    /**
     * The Results model constructor.
     * @property {module:model/Results}
     */
    Results,

    /**
    * The EdgeFunctionsApi service constructor.
    * @property {module:api/EdgeFunctionsApi}
    */
    EdgeFunctionsApi
};
