/**
 * Purge API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PurgeUrlRequest model module.
 * @module model/PurgeUrlRequest
 * @version 1.0.0
 */
class PurgeUrlRequest {
    /**
     * Constructs a new <code>PurgeUrlRequest</code>.
     * @alias module:model/PurgeUrlRequest
     * @param urls {Array.<String>} 
     * @param method {String} 
     */
    constructor(urls, method) { 
        
        PurgeUrlRequest.initialize(this, urls, method);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, urls, method) { 
        obj['urls'] = urls;
        obj['method'] = method;
    }

    /**
     * Constructs a <code>PurgeUrlRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PurgeUrlRequest} obj Optional instance to populate.
     * @return {module:model/PurgeUrlRequest} The populated <code>PurgeUrlRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PurgeUrlRequest();

            if (data.hasOwnProperty('urls')) {
                obj['urls'] = ApiClient.convertToType(data['urls'], ['String']);
            }
            if (data.hasOwnProperty('method')) {
                obj['method'] = ApiClient.convertToType(data['method'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PurgeUrlRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PurgeUrlRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PurgeUrlRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['urls'])) {
            throw new Error("Expected the field `urls` to be an array in the JSON data but got " + data['urls']);
        }
        // ensure the json data is a string
        if (data['method'] && !(typeof data['method'] === 'string' || data['method'] instanceof String)) {
            throw new Error("Expected the field `method` to be a primitive type in the JSON string but got " + data['method']);
        }

        return true;
    }


}

PurgeUrlRequest.RequiredProperties = ["urls", "method"];

/**
 * @member {Array.<String>} urls
 */
PurgeUrlRequest.prototype['urls'] = undefined;

/**
 * @member {String} method
 */
PurgeUrlRequest.prototype['method'] = undefined;






export default PurgeUrlRequest;

