/**
 * Edge Firewall API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EdgeFirewall from './EdgeFirewall';
import Links from './Links';

/**
 * The ListEdgeFirewallResponse model module.
 * @module model/ListEdgeFirewallResponse
 * @version 2.0.0
 */
class ListEdgeFirewallResponse {
    /**
     * Constructs a new <code>ListEdgeFirewallResponse</code>.
     * @alias module:model/ListEdgeFirewallResponse
     */
    constructor() { 
        
        ListEdgeFirewallResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListEdgeFirewallResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListEdgeFirewallResponse} obj Optional instance to populate.
     * @return {module:model/ListEdgeFirewallResponse} The populated <code>ListEdgeFirewallResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListEdgeFirewallResponse();

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('total_pages')) {
                obj['total_pages'] = ApiClient.convertToType(data['total_pages'], 'Number');
            }
            if (data.hasOwnProperty('schema_version')) {
                obj['schema_version'] = ApiClient.convertToType(data['schema_version'], 'Number');
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = Links.constructFromObject(data['links']);
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [EdgeFirewall]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListEdgeFirewallResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListEdgeFirewallResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `links`
        if (data['links']) { // data not null
          Links.validateJSON(data['links']);
        }
        if (data['results']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['results'])) {
                throw new Error("Expected the field `results` to be an array in the JSON data but got " + data['results']);
            }
            // validate the optional field `results` (array)
            for (const item of data['results']) {
                EdgeFirewall.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Number} count
 */
ListEdgeFirewallResponse.prototype['count'] = undefined;

/**
 * @member {Number} total_pages
 */
ListEdgeFirewallResponse.prototype['total_pages'] = undefined;

/**
 * @member {Number} schema_version
 */
ListEdgeFirewallResponse.prototype['schema_version'] = undefined;

/**
 * @member {module:model/Links} links
 */
ListEdgeFirewallResponse.prototype['links'] = undefined;

/**
 * @member {Array.<module:model/EdgeFirewall>} results
 */
ListEdgeFirewallResponse.prototype['results'] = undefined;






export default ListEdgeFirewallResponse;

