/**
 * Edge Firewall API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RuleSetResultResults from './RuleSetResultResults';

/**
 * The RuleSetResult model module.
 * @module model/RuleSetResult
 * @version 2.0.0
 */
class RuleSetResult {
    /**
     * Constructs a new <code>RuleSetResult</code>.
     * @alias module:model/RuleSetResult
     */
    constructor() { 
        
        RuleSetResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RuleSetResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RuleSetResult} obj Optional instance to populate.
     * @return {module:model/RuleSetResult} The populated <code>RuleSetResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RuleSetResult();

            if (data.hasOwnProperty('results')) {
                obj['results'] = RuleSetResultResults.constructFromObject(data['results']);
            }
            if (data.hasOwnProperty('schema_version')) {
                obj['schema_version'] = ApiClient.convertToType(data['schema_version'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RuleSetResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RuleSetResult</code>.
     */
    static validateJSON(data) {
        // validate the optional field `results`
        if (data['results']) { // data not null
          RuleSetResultResults.validateJSON(data['results']);
        }

        return true;
    }


}



/**
 * @member {module:model/RuleSetResultResults} results
 */
RuleSetResult.prototype['results'] = undefined;

/**
 * @member {Number} schema_version
 */
RuleSetResult.prototype['schema_version'] = undefined;






export default RuleSetResult;

