/**
 * Edge Firewall API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Variables.
* @enum {}
* @readonly
*/
export default class Variables {
    
        /**
         * value: "header_accept"
         * @const
         */
        "header_accept" = "header_accept";

    
        /**
         * value: "header_accept_encoding"
         * @const
         */
        "header_accept_encoding" = "header_accept_encoding";

    
        /**
         * value: "header_accept_language"
         * @const
         */
        "header_accept_language" = "header_accept_language";

    
        /**
         * value: "header_cookie"
         * @const
         */
        "header_cookie" = "header_cookie";

    
        /**
         * value: "header_origin"
         * @const
         */
        "header_origin" = "header_origin";

    
        /**
         * value: "header_referer"
         * @const
         */
        "header_referer" = "header_referer";

    
        /**
         * value: "header_user_agent"
         * @const
         */
        "header_user_agent" = "header_user_agent";

    
        /**
         * value: "host"
         * @const
         */
        "host" = "host";

    
        /**
         * value: "network"
         * @const
         */
        "network" = "network";

    
        /**
         * value: "request_args"
         * @const
         */
        "request_args" = "request_args";

    
        /**
         * value: "request_method"
         * @const
         */
        "request_method" = "request_method";

    
        /**
         * value: "request_uri"
         * @const
         */
        "request_uri" = "request_uri";

    
        /**
         * value: "scheme"
         * @const
         */
        "scheme" = "scheme";

    
        /**
         * value: "client_certificate_validation"
         * @const
         */
        "client_certificate_validation" = "client_certificate_validation";

    

    /**
    * Returns a <code>Variables</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Variables} The enum <code>Variables</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

