/**
 * Edge Application API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ApplicationCacheCreateRequest from './model/ApplicationCacheCreateRequest';
import ApplicationCacheCreateResponse from './model/ApplicationCacheCreateResponse';
import ApplicationCacheCreateResults from './model/ApplicationCacheCreateResults';
import ApplicationCacheGetOneResponse from './model/ApplicationCacheGetOneResponse';
import ApplicationCacheGetResponse from './model/ApplicationCacheGetResponse';
import ApplicationCachePatchRequest from './model/ApplicationCachePatchRequest';
import ApplicationCachePatchResponse from './model/ApplicationCachePatchResponse';
import ApplicationCachePutRequest from './model/ApplicationCachePutRequest';
import ApplicationCachePutResponse from './model/ApplicationCachePutResponse';
import ApplicationCacheResponseDetails from './model/ApplicationCacheResponseDetails';
import ApplicationCacheResults from './model/ApplicationCacheResults';
import ApplicationCreateInstanceRequest from './model/ApplicationCreateInstanceRequest';
import ApplicationInstanceResults from './model/ApplicationInstanceResults';
import ApplicationInstancesGetOneResponse from './model/ApplicationInstancesGetOneResponse';
import ApplicationInstancesGetResponse from './model/ApplicationInstancesGetResponse';
import ApplicationInstancesResults from './model/ApplicationInstancesResults';
import ApplicationLinks from './model/ApplicationLinks';
import ApplicationOrigins from './model/ApplicationOrigins';
import ApplicationPutInstanceRequest from './model/ApplicationPutInstanceRequest';
import ApplicationPutRequest from './model/ApplicationPutRequest';
import ApplicationPutResult from './model/ApplicationPutResult';
import ApplicationResults from './model/ApplicationResults';
import ApplicationResultsCreate from './model/ApplicationResultsCreate';
import ApplicationUpdateInstanceRequest from './model/ApplicationUpdateInstanceRequest';
import ApplicationUpdateRequest from './model/ApplicationUpdateRequest';
import ApplicationUpdateResponse from './model/ApplicationUpdateResponse';
import ApplicationUpdateResults from './model/ApplicationUpdateResults';
import ApplicationsResults from './model/ApplicationsResults';
import CreateApplicationRequest from './model/CreateApplicationRequest';
import CreateApplicationResult from './model/CreateApplicationResult';
import CreateDeviceGroupsRequest from './model/CreateDeviceGroupsRequest';
import CreateOriginsRequest from './model/CreateOriginsRequest';
import CreateOriginsRequestAddresses from './model/CreateOriginsRequestAddresses';
import CreateRulesEngineRequest from './model/CreateRulesEngineRequest';
import DeviceGroupsIdResponse from './model/DeviceGroupsIdResponse';
import DeviceGroupsResponse from './model/DeviceGroupsResponse';
import DeviceGroupsResponseLinks from './model/DeviceGroupsResponseLinks';
import DeviceGroupsResultResponse from './model/DeviceGroupsResultResponse';
import GetApplicationResponse from './model/GetApplicationResponse';
import OriginsIdResponse from './model/OriginsIdResponse';
import OriginsResponse from './model/OriginsResponse';
import OriginsResponseLinks from './model/OriginsResponseLinks';
import OriginsResultResponse from './model/OriginsResultResponse';
import OriginsResultResponseAddresses from './model/OriginsResultResponseAddresses';
import PatchDeviceGroupsRequest from './model/PatchDeviceGroupsRequest';
import PatchOriginsRequest from './model/PatchOriginsRequest';
import PatchRulesEngineRequest from './model/PatchRulesEngineRequest';
import RulesEngineBehavior from './model/RulesEngineBehavior';
import RulesEngineCriteria from './model/RulesEngineCriteria';
import RulesEngineIdResponse from './model/RulesEngineIdResponse';
import RulesEngineResponse from './model/RulesEngineResponse';
import RulesEngineResultResponse from './model/RulesEngineResultResponse';
import RulesEngineResultResponseBehaviors from './model/RulesEngineResultResponseBehaviors';
import UpdateDeviceGroupsRequest from './model/UpdateDeviceGroupsRequest';
import UpdateOriginsRequest from './model/UpdateOriginsRequest';
import UpdateRulesEngineRequest from './model/UpdateRulesEngineRequest';
import EdgeApplicationsCacheSettingsApi from './api/EdgeApplicationsCacheSettingsApi';
import EdgeApplicationsDeviceGroupsApi from './api/EdgeApplicationsDeviceGroupsApi';
import EdgeApplicationsEdgeFunctionsInstancesApi from './api/EdgeApplicationsEdgeFunctionsInstancesApi';
import EdgeApplicationsMainSettingsApi from './api/EdgeApplicationsMainSettingsApi';
import EdgeApplicationsOriginsApi from './api/EdgeApplicationsOriginsApi';
import EdgeApplicationsRulesEngineApi from './api/EdgeApplicationsRulesEngineApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var EdgeApplicationApi = require('index'); // See note below*.
* var xxxSvc = new EdgeApplicationApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new EdgeApplicationApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new EdgeApplicationApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new EdgeApplicationApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ApplicationCacheCreateRequest model constructor.
     * @property {module:model/ApplicationCacheCreateRequest}
     */
    ApplicationCacheCreateRequest,

    /**
     * The ApplicationCacheCreateResponse model constructor.
     * @property {module:model/ApplicationCacheCreateResponse}
     */
    ApplicationCacheCreateResponse,

    /**
     * The ApplicationCacheCreateResults model constructor.
     * @property {module:model/ApplicationCacheCreateResults}
     */
    ApplicationCacheCreateResults,

    /**
     * The ApplicationCacheGetOneResponse model constructor.
     * @property {module:model/ApplicationCacheGetOneResponse}
     */
    ApplicationCacheGetOneResponse,

    /**
     * The ApplicationCacheGetResponse model constructor.
     * @property {module:model/ApplicationCacheGetResponse}
     */
    ApplicationCacheGetResponse,

    /**
     * The ApplicationCachePatchRequest model constructor.
     * @property {module:model/ApplicationCachePatchRequest}
     */
    ApplicationCachePatchRequest,

    /**
     * The ApplicationCachePatchResponse model constructor.
     * @property {module:model/ApplicationCachePatchResponse}
     */
    ApplicationCachePatchResponse,

    /**
     * The ApplicationCachePutRequest model constructor.
     * @property {module:model/ApplicationCachePutRequest}
     */
    ApplicationCachePutRequest,

    /**
     * The ApplicationCachePutResponse model constructor.
     * @property {module:model/ApplicationCachePutResponse}
     */
    ApplicationCachePutResponse,

    /**
     * The ApplicationCacheResponseDetails model constructor.
     * @property {module:model/ApplicationCacheResponseDetails}
     */
    ApplicationCacheResponseDetails,

    /**
     * The ApplicationCacheResults model constructor.
     * @property {module:model/ApplicationCacheResults}
     */
    ApplicationCacheResults,

    /**
     * The ApplicationCreateInstanceRequest model constructor.
     * @property {module:model/ApplicationCreateInstanceRequest}
     */
    ApplicationCreateInstanceRequest,

    /**
     * The ApplicationInstanceResults model constructor.
     * @property {module:model/ApplicationInstanceResults}
     */
    ApplicationInstanceResults,

    /**
     * The ApplicationInstancesGetOneResponse model constructor.
     * @property {module:model/ApplicationInstancesGetOneResponse}
     */
    ApplicationInstancesGetOneResponse,

    /**
     * The ApplicationInstancesGetResponse model constructor.
     * @property {module:model/ApplicationInstancesGetResponse}
     */
    ApplicationInstancesGetResponse,

    /**
     * The ApplicationInstancesResults model constructor.
     * @property {module:model/ApplicationInstancesResults}
     */
    ApplicationInstancesResults,

    /**
     * The ApplicationLinks model constructor.
     * @property {module:model/ApplicationLinks}
     */
    ApplicationLinks,

    /**
     * The ApplicationOrigins model constructor.
     * @property {module:model/ApplicationOrigins}
     */
    ApplicationOrigins,

    /**
     * The ApplicationPutInstanceRequest model constructor.
     * @property {module:model/ApplicationPutInstanceRequest}
     */
    ApplicationPutInstanceRequest,

    /**
     * The ApplicationPutRequest model constructor.
     * @property {module:model/ApplicationPutRequest}
     */
    ApplicationPutRequest,

    /**
     * The ApplicationPutResult model constructor.
     * @property {module:model/ApplicationPutResult}
     */
    ApplicationPutResult,

    /**
     * The ApplicationResults model constructor.
     * @property {module:model/ApplicationResults}
     */
    ApplicationResults,

    /**
     * The ApplicationResultsCreate model constructor.
     * @property {module:model/ApplicationResultsCreate}
     */
    ApplicationResultsCreate,

    /**
     * The ApplicationUpdateInstanceRequest model constructor.
     * @property {module:model/ApplicationUpdateInstanceRequest}
     */
    ApplicationUpdateInstanceRequest,

    /**
     * The ApplicationUpdateRequest model constructor.
     * @property {module:model/ApplicationUpdateRequest}
     */
    ApplicationUpdateRequest,

    /**
     * The ApplicationUpdateResponse model constructor.
     * @property {module:model/ApplicationUpdateResponse}
     */
    ApplicationUpdateResponse,

    /**
     * The ApplicationUpdateResults model constructor.
     * @property {module:model/ApplicationUpdateResults}
     */
    ApplicationUpdateResults,

    /**
     * The ApplicationsResults model constructor.
     * @property {module:model/ApplicationsResults}
     */
    ApplicationsResults,

    /**
     * The CreateApplicationRequest model constructor.
     * @property {module:model/CreateApplicationRequest}
     */
    CreateApplicationRequest,

    /**
     * The CreateApplicationResult model constructor.
     * @property {module:model/CreateApplicationResult}
     */
    CreateApplicationResult,

    /**
     * The CreateDeviceGroupsRequest model constructor.
     * @property {module:model/CreateDeviceGroupsRequest}
     */
    CreateDeviceGroupsRequest,

    /**
     * The CreateOriginsRequest model constructor.
     * @property {module:model/CreateOriginsRequest}
     */
    CreateOriginsRequest,

    /**
     * The CreateOriginsRequestAddresses model constructor.
     * @property {module:model/CreateOriginsRequestAddresses}
     */
    CreateOriginsRequestAddresses,

    /**
     * The CreateRulesEngineRequest model constructor.
     * @property {module:model/CreateRulesEngineRequest}
     */
    CreateRulesEngineRequest,

    /**
     * The DeviceGroupsIdResponse model constructor.
     * @property {module:model/DeviceGroupsIdResponse}
     */
    DeviceGroupsIdResponse,

    /**
     * The DeviceGroupsResponse model constructor.
     * @property {module:model/DeviceGroupsResponse}
     */
    DeviceGroupsResponse,

    /**
     * The DeviceGroupsResponseLinks model constructor.
     * @property {module:model/DeviceGroupsResponseLinks}
     */
    DeviceGroupsResponseLinks,

    /**
     * The DeviceGroupsResultResponse model constructor.
     * @property {module:model/DeviceGroupsResultResponse}
     */
    DeviceGroupsResultResponse,

    /**
     * The GetApplicationResponse model constructor.
     * @property {module:model/GetApplicationResponse}
     */
    GetApplicationResponse,

    /**
     * The OriginsIdResponse model constructor.
     * @property {module:model/OriginsIdResponse}
     */
    OriginsIdResponse,

    /**
     * The OriginsResponse model constructor.
     * @property {module:model/OriginsResponse}
     */
    OriginsResponse,

    /**
     * The OriginsResponseLinks model constructor.
     * @property {module:model/OriginsResponseLinks}
     */
    OriginsResponseLinks,

    /**
     * The OriginsResultResponse model constructor.
     * @property {module:model/OriginsResultResponse}
     */
    OriginsResultResponse,

    /**
     * The OriginsResultResponseAddresses model constructor.
     * @property {module:model/OriginsResultResponseAddresses}
     */
    OriginsResultResponseAddresses,

    /**
     * The PatchDeviceGroupsRequest model constructor.
     * @property {module:model/PatchDeviceGroupsRequest}
     */
    PatchDeviceGroupsRequest,

    /**
     * The PatchOriginsRequest model constructor.
     * @property {module:model/PatchOriginsRequest}
     */
    PatchOriginsRequest,

    /**
     * The PatchRulesEngineRequest model constructor.
     * @property {module:model/PatchRulesEngineRequest}
     */
    PatchRulesEngineRequest,

    /**
     * The RulesEngineBehavior model constructor.
     * @property {module:model/RulesEngineBehavior}
     */
    RulesEngineBehavior,

    /**
     * The RulesEngineCriteria model constructor.
     * @property {module:model/RulesEngineCriteria}
     */
    RulesEngineCriteria,

    /**
     * The RulesEngineIdResponse model constructor.
     * @property {module:model/RulesEngineIdResponse}
     */
    RulesEngineIdResponse,

    /**
     * The RulesEngineResponse model constructor.
     * @property {module:model/RulesEngineResponse}
     */
    RulesEngineResponse,

    /**
     * The RulesEngineResultResponse model constructor.
     * @property {module:model/RulesEngineResultResponse}
     */
    RulesEngineResultResponse,

    /**
     * The RulesEngineResultResponseBehaviors model constructor.
     * @property {module:model/RulesEngineResultResponseBehaviors}
     */
    RulesEngineResultResponseBehaviors,

    /**
     * The UpdateDeviceGroupsRequest model constructor.
     * @property {module:model/UpdateDeviceGroupsRequest}
     */
    UpdateDeviceGroupsRequest,

    /**
     * The UpdateOriginsRequest model constructor.
     * @property {module:model/UpdateOriginsRequest}
     */
    UpdateOriginsRequest,

    /**
     * The UpdateRulesEngineRequest model constructor.
     * @property {module:model/UpdateRulesEngineRequest}
     */
    UpdateRulesEngineRequest,

    /**
    * The EdgeApplicationsCacheSettingsApi service constructor.
    * @property {module:api/EdgeApplicationsCacheSettingsApi}
    */
    EdgeApplicationsCacheSettingsApi,

    /**
    * The EdgeApplicationsDeviceGroupsApi service constructor.
    * @property {module:api/EdgeApplicationsDeviceGroupsApi}
    */
    EdgeApplicationsDeviceGroupsApi,

    /**
    * The EdgeApplicationsEdgeFunctionsInstancesApi service constructor.
    * @property {module:api/EdgeApplicationsEdgeFunctionsInstancesApi}
    */
    EdgeApplicationsEdgeFunctionsInstancesApi,

    /**
    * The EdgeApplicationsMainSettingsApi service constructor.
    * @property {module:api/EdgeApplicationsMainSettingsApi}
    */
    EdgeApplicationsMainSettingsApi,

    /**
    * The EdgeApplicationsOriginsApi service constructor.
    * @property {module:api/EdgeApplicationsOriginsApi}
    */
    EdgeApplicationsOriginsApi,

    /**
    * The EdgeApplicationsRulesEngineApi service constructor.
    * @property {module:api/EdgeApplicationsRulesEngineApi}
    */
    EdgeApplicationsRulesEngineApi
};
