/**
 * Domain API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import CreateDomainRequest from './model/CreateDomainRequest';
import DomainLinks from './model/DomainLinks';
import DomainResponseWithResult from './model/DomainResponseWithResult';
import DomainResponseWithResults from './model/DomainResponseWithResults';
import DomainResults from './model/DomainResults';
import PutDomainRequest from './model/PutDomainRequest';
import UpdateDomainRequest from './model/UpdateDomainRequest';
import DomainsApi from './api/DomainsApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var DomainApi = require('index'); // See note below*.
* var xxxSvc = new DomainApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new DomainApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new DomainApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new DomainApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The CreateDomainRequest model constructor.
     * @property {module:model/CreateDomainRequest}
     */
    CreateDomainRequest,

    /**
     * The DomainLinks model constructor.
     * @property {module:model/DomainLinks}
     */
    DomainLinks,

    /**
     * The DomainResponseWithResult model constructor.
     * @property {module:model/DomainResponseWithResult}
     */
    DomainResponseWithResult,

    /**
     * The DomainResponseWithResults model constructor.
     * @property {module:model/DomainResponseWithResults}
     */
    DomainResponseWithResults,

    /**
     * The DomainResults model constructor.
     * @property {module:model/DomainResults}
     */
    DomainResults,

    /**
     * The PutDomainRequest model constructor.
     * @property {module:model/PutDomainRequest}
     */
    PutDomainRequest,

    /**
     * The UpdateDomainRequest model constructor.
     * @property {module:model/UpdateDomainRequest}
     */
    UpdateDomainRequest,

    /**
    * The DomainsApi service constructor.
    * @property {module:api/DomainsApi}
    */
    DomainsApi
};
