/**
 * Edge Firewall API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EdgeFirewallApi);
  }
}(this, function(expect, EdgeFirewallApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EdgeFirewallApi.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('edgeFirewallGet', function() {
      it('should call edgeFirewallGet successfully', function(done) {
        //uncomment below and update the code to test edgeFirewallGet
        //instance.edgeFirewallGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('edgeFirewallPost', function() {
      it('should call edgeFirewallPost successfully', function(done) {
        //uncomment below and update the code to test edgeFirewallPost
        //instance.edgeFirewallPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('edgeFirewallUuidDelete', function() {
      it('should call edgeFirewallUuidDelete successfully', function(done) {
        //uncomment below and update the code to test edgeFirewallUuidDelete
        //instance.edgeFirewallUuidDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('edgeFirewallUuidGet', function() {
      it('should call edgeFirewallUuidGet successfully', function(done) {
        //uncomment below and update the code to test edgeFirewallUuidGet
        //instance.edgeFirewallUuidGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('edgeFirewallUuidPatch', function() {
      it('should call edgeFirewallUuidPatch successfully', function(done) {
        //uncomment below and update the code to test edgeFirewallUuidPatch
        //instance.edgeFirewallUuidPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('edgeFirewallUuidPut', function() {
      it('should call edgeFirewallUuidPut successfully', function(done) {
        //uncomment below and update the code to test edgeFirewallUuidPut
        //instance.edgeFirewallUuidPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
